version: "3"

services:
  sut:
    build:
      context: .
      dockerfile: Dockerfile.test
    command: pytest
    environment:
      - DB_SERVER=mongodbdocker
    depends_on:
      - mongodbdocker

  mongodbdocker:
    image: mongo:bionic
